"use strict";
/**
 * lib/geometry.js
 *
 * Polygon triangulation (earcut), extrusion, and Wavefront .obj writing.
 * Data-source-agnostic: operates on already-projected/recentered [x, y]
 * rings, so this module would be directly reusable by a future
 * Overture-sourced Node script the same way solarch_3d_common.py's
 * equivalents are shared by both Python scripts.
 */

const fs = require("fs");
const earcut = require("earcut").default;

/** Triangulate a polygon (with optional holes) using earcut.
 * Returns { points2d, tris } where points2d is an array of [x, y] and
 * tris is an array of [a, b, c] indices into points2d. */
function triangulateFootprint(ext, holes) {
  const rings = [ext, ...holes];
  const verts = [];
  const holeIndices = [];
  let vertexCount = 0;
  for (let i = 0; i < rings.length; i++) {
    if (i > 0) holeIndices.push(vertexCount);
    for (const [x, y] of rings[i]) {
      verts.push(x, y);
      vertexCount++;
    }
  }
  const triFlat = earcut(verts, holeIndices.length ? holeIndices : undefined, 2);
  const points2d = [];
  for (let i = 0; i < verts.length; i += 2) points2d.push([verts[i], verts[i + 1]]);
  const tris = [];
  for (let i = 0; i < triFlat.length; i += 3) tris.push([triFlat[i], triFlat[i + 1], triFlat[i + 2]]);
  return { points2d, tris };
}

/** Accumulates vertices/faces and writes a Wavefront .obj file. OBJ
 * indices are 1-based. Includes the hard guard against ever writing a
 * non-finite vertex. */
class ObjWriter {
  constructor() {
    this.vertices = []; // array of [x, y, z]
    this.faces = []; // array of arrays of 1-based vertex indices
    this.groups = []; // array of [faceStartIndex, name]
  }

  addVertex(x, y, z) {
    if (!(Number.isFinite(x) && Number.isFinite(y) && Number.isFinite(z))) {
      throw new Error(`Refusing to write non-finite vertex (${x}, ${y}, ${z})`);
    }
    this.vertices.push([x, y, z]);
    return this.vertices.length; // 1-based index of the vertex just added
  }

  addFace(idxs) {
    this.faces.push(idxs);
  }

  startGroup(name) {
    this.groups.push([this.faces.length, name]);
  }

  write(filePath, generator = "SOLARCHVISION_OSM_3D_in_obj.js") {
    const groupAt = new Map(this.groups.map(([start, name]) => [start, name]));
    const lines = [];
    lines.push(`# Generated by ${generator}`);
    lines.push(`# ${this.vertices.length} vertices, ${this.faces.length} faces`);
    for (const [x, y, z] of this.vertices) {
      lines.push(`v ${x.toFixed(4)} ${y.toFixed(4)} ${z.toFixed(4)}`);
    }
    for (let i = 0; i < this.faces.length; i++) {
      if (groupAt.has(i)) lines.push(`g ${groupAt.get(i)}`);
      lines.push("f " + this.faces[i].join(" "));
    }
    fs.writeFileSync(filePath, lines.join("\n") + "\n");
  }
}

/** Extrude a single (possibly holed) 2D footprint polygon into a closed
 * 3D solid from z=baseZ to z=baseZ+height, and append it to the
 * ObjWriter. ext/holes: arrays of [x, y], as returned by
 * polygonRingsFromGeoJSON. baseZ defaults to 0 (OSM buildings always
 * sit at ground level; an Overture-sourced caller could pass a non-zero
 * baseZ for a "floating" building part, same idea as
 * solarch_3d_common.py's add_extruded_polygon). */
function addExtrudedPolygon(writer, ext, holes, height, baseZ = 0.0) {
  if (ext.length < 3) return;

  let points2d, tris;
  try {
    ({ points2d, tris } = triangulateFootprint(ext, holes));
  } catch (e) {
    return; // skip malformed geometry rather than aborting the whole run
  }
  if (tris.length === 0) return;

  const n = points2d.length;
  const topZ = baseZ + height;

  // Bottom vertices (z=baseZ) and top vertices (z=topZ), same local xy order
  const bottomStart = writer.addVertex(points2d[0][0], points2d[0][1], baseZ);
  for (let i = 1; i < n; i++) writer.addVertex(points2d[i][0], points2d[i][1], baseZ);
  const topStart = writer.addVertex(points2d[0][0], points2d[0][1], topZ);
  for (let i = 1; i < n; i++) writer.addVertex(points2d[i][0], points2d[i][1], topZ);

  // Bottom cap: reverse winding so the normal points down/outward
  for (const [a, b, c] of tris) {
    writer.addFace([bottomStart + a, bottomStart + c, bottomStart + b]);
  }
  // Top cap: original winding faces up
  for (const [a, b, c] of tris) {
    writer.addFace([topStart + a, topStart + b, topStart + c]);
  }

  // Walls: one quad (as 2 triangles) per edge of every ring (exterior + holes)
  let offset = 0;
  for (const ring of [ext, ...holes]) {
    const m = ring.length;
    for (let i = 0; i < m; i++) {
      const j = (i + 1) % m;
      const b0 = bottomStart + offset + i;
      const b1 = bottomStart + offset + j;
      const t0 = topStart + offset + i;
      const t1 = topStart + offset + j;
      writer.addFace([b0, b1, t1]);
      writer.addFace([b0, t1, t0]);
    }
    offset += m;
  }
}

function iterPolygons(geometry) {
  if (!geometry) return [];
  if (geometry.type === "Polygon") return [geometry.coordinates];
  if (geometry.type === "MultiPolygon") return geometry.coordinates;
  return [];
}

// -----------------------------------------------------------------------
// buildings.svs: SOLARCHVISION_BIM's own "Mesh" script command
// (src/solarchvision_bim/runScript.pde's `case "MESH":`, calling
// Create3D.pde's add_Mesh) natively supports a face with any number of
// vertices - unlike buildings.obj, a hole-free cap here does NOT need
// triangulating: the whole ring becomes one Mesh line. A footprint WITH
// holes (a courtyard) still has to be triangulated for its caps, same as
// the OBJ path - a single n-gon face can't represent an annulus. Walls
// are always a plain quad either way, hole or not. Mirrors
// solarch_3d_common.py's MeshWriter/add_extruded_mesh exactly (same
// line format, same winding conventions).
//
//   Mesh m:7 tes:0 lyr:0 x1,y1,z1 x2,y2,z2 x3,y3,z3 ...
// -----------------------------------------------------------------------

/** Accumulates 'Mesh ...' command lines for buildings.svs. */
class MeshWriter {
  constructor() {
    this.lines = [];
  }

  /** points: array of [x, y, z], at least 3, in order around the face
   * (no closing repeat of the first point). */
  addFace(points, m, tes, lyr) {
    if (points.length < 3) return;
    for (const [x, y, z] of points) {
      if (!(Number.isFinite(x) && Number.isFinite(y) && Number.isFinite(z))) {
        throw new Error(`Refusing to write non-finite vertex (${x}, ${y}, ${z})`);
      }
    }
    const ptsStr = points.map(([x, y, z]) => `${x.toFixed(4)},${y.toFixed(4)},${z.toFixed(4)}`).join(" ");
    this.lines.push(`Mesh m:${m} tes:${tes} lyr:${lyr} ${ptsStr}`);
  }

  write(filePath) {
    fs.writeFileSync(filePath, this.lines.join("\n") + (this.lines.length ? "\n" : ""));
  }
}

/** Same extruded solid as addExtrudedPolygon, but as buildings.svs Mesh
 * lines: hole-free caps are one n-gon face each (no triangulation); caps
 * with holes are triangulated (see module comment above). */
function addExtrudedMesh(writer, ext, holes, height, baseZ = 0.0, m = 7, tes = 0, lyr = 0) {
  if (ext.length < 3) return;
  const topZ = baseZ + height;

  if (holes.length === 0) {
    // Bottom cap: reversed winding, one n-gon face, faces down/outward.
    writer.addFace([...ext].reverse().map(([x, y]) => [x, y, baseZ]), m, tes, lyr);
    // Top cap: natural winding, one n-gon face, faces up.
    writer.addFace(ext.map(([x, y]) => [x, y, topZ]), m, tes, lyr);
  } else {
    let points2d, tris;
    try {
      ({ points2d, tris } = triangulateFootprint(ext, holes));
    } catch (e) {
      points2d = null;
      tris = [];
    }
    if (points2d && tris.length > 0) {
      for (const [a, b, c] of tris) {
        const [xa, ya] = points2d[a];
        const [xb, yb] = points2d[b];
        const [xc, yc] = points2d[c];
        // Bottom: reversed winding. Top: natural winding.
        writer.addFace([[xa, ya, baseZ], [xc, yc, baseZ], [xb, yb, baseZ]], m, tes, lyr);
        writer.addFace([[xa, ya, topZ], [xb, yb, topZ], [xc, yc, topZ]], m, tes, lyr);
      }
    }
  }

  // Walls: one quad per edge, for every ring (exterior + holes) - same
  // (b0, b1, t1, t0) corner order as addExtrudedPolygon's two wall
  // triangles combined, just kept as one 4-vertex face here.
  for (const ring of [ext, ...holes]) {
    const n = ring.length;
    for (let i = 0; i < n; i++) {
      const j = (i + 1) % n;
      const [x0, y0] = ring[i];
      const [x1, y1] = ring[j];
      writer.addFace(
        [
          [x0, y0, baseZ],
          [x1, y1, baseZ],
          [x1, y1, topZ],
          [x0, y0, topZ],
        ],
        m, tes, lyr
      );
    }
  }
}

module.exports = { triangulateFootprint, ObjWriter, addExtrudedPolygon, iterPolygons, MeshWriter, addExtrudedMesh };
